export const learningCategories = [
  {
    name: "حيوانات المزرعة",
    image: "/images/learn-names/farm-animals/category.jpeg",
    items: [
      {
        name: "بقرة",
        enName: "Cow",
        frName: "Vache",
        sound: "/sounds/learn-names/ar/farm-animals/cow.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/cow.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/cow.mp3",
        itemSound: "/sounds/learn-names/other/cow.mp3",
        image: "/images/learn-names/farm-animals/cow.png",
      },
      {
        name: "خروف",
        enName: "Sheep",
        frName: "Mouton",
        sound: "/sounds/learn-names/ar/farm-animals/sheep.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/sheep.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/sheep.mp3",
        itemSound: "/sounds/learn-names/other/sheep.mp3",
        image: "/images/learn-names/farm-animals/sheep.png",
      },
      {
        name: "دجاجة",
        enName: "Chicken",
        frName: "Poulet",
        sound: "/sounds/learn-names/ar/farm-animals/chicken.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/chicken.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/chicken.mp3",
        itemSound: "/sounds/learn-names/other/chicken.mp3",
        image: "/images/learn-names/farm-animals/chicken.png",
      },
      {
        name: "حصان",
        enName: "Horse",
        frName: "Cheval",
        sound: "/sounds/learn-names/ar/farm-animals/horse.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/horse.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/horse.mp3",
        itemSound: "/sounds/learn-names/other/horse.mp3",
        image: "/images/learn-names/farm-animals/horse.png",
      },
      {
        name: "حمار",
        enName: "Donkey",
        frName: "Âne",
        sound: "/sounds/learn-names/ar/farm-animals/donkey.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/donkey.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/donkey.mp3",
        itemSound: "/sounds/learn-names/other/donkey.mp3",
        image: "/images/learn-names/farm-animals/donkey.png",
      },
      {
        name: "جذي",
        enName: "Goat",
        frName: "Chèvre",
        sound: "/sounds/learn-names/ar/farm-animals/goat.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/goat.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/goat.mp3",
        itemSound: null,
        image: "/images/learn-names/farm-animals/goat.png",
      },
      {
        name: "بطة",
        enName: "Duck",
        frName: "Canard",
        sound: "/sounds/learn-names/ar/farm-animals/duck.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/duck.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/duck.mp3",
        itemSound: null,
        image: "/images/learn-names/farm-animals/duck.png",
      },
      {
        name: "أرنب",
        enName: "Rabbit",
        frName: "Lapin",
        sound: "/sounds/learn-names/ar/farm-animals/rabbit.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/rabbit.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/rabbit.mp3",
        itemSound: null,
        image: "/images/learn-names/farm-animals/rabbit.png",
      },
      {
        name: "قطة",
        enName: "Cat",
        frName: "Chat",
        sound: "/sounds/learn-names/ar/farm-animals/cat.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/cat.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/cat.mp3",
        itemSound: "/sounds/learn-names/other/cat.mp3",
        image: "/images/learn-names/farm-animals/cat.png",
      },
      {
        name: "كلب",
        enName: "Dog",
        frName: "Chien",
        sound: "/sounds/learn-names/ar/farm-animals/dog.mp3",
        enSound: "/sounds/learn-names/en/farm-animals/dog.mp3",
        frSound: "/sounds/learn-names/fr/farm-animals/dog.mp3",
        itemSound: "/sounds/learn-names/other/dog.mp3",
        image: "/images/learn-names/farm-animals/dog.png",
      },
    ],
  },
  {
    name: "حيوانات البرية",
    image: "/images/learn-names/wild-animals/category.jpg",
    items: [
      {
        name: "أسد",
        enName: "Lion",
        frName: "Lion",
        sound: "/sounds/learn-names/ar/wild-animals/lion.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/lion.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/lion.mp3",
        itemSound: "/sounds/learn-names/other/lion.mp3",
        image: "/images/learn-names/wild-animals/lion.png",
      },
      {
        name: "نمر",
        enName: "Tiger",
        frName: "Tigre",
        sound: "/sounds/learn-names/ar/wild-animals/tiger.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/tiger.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/tiger.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/tiger.png",
      },
      {
        name: "فيل",
        enName: "Elephant",
        frName: "Éléphant",
        sound: "/sounds/learn-names/ar/wild-animals/elephant.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/elephant.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/elephant.mp3",
        itemSound: "/sounds/learn-names/other/elephant.mp3",
        image: "/images/learn-names/wild-animals/elephant.png",
      },
      {
        name: "زرافة",
        enName: "Giraffe",
        frName: "Girafe",
        sound: "/sounds/learn-names/ar/wild-animals/giraffe.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/giraffe.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/giraffe.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/giraffe.png",
      },
      {
        name: "قرد",
        enName: "Monkey",
        frName: "Singe",
        sound: "/sounds/learn-names/ar/wild-animals/monkey.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/monkey.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/monkey.mp3",
        itemSound: "/sounds/learn-names/other/monkey.mp3",
        image: "/images/learn-names/wild-animals/monkey.png",
      },
      {
        name: "دب",
        enName: "Bear",
        frName: "Ours",
        sound: "/sounds/learn-names/ar/wild-animals/bear.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/bear.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/bear.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/bear.png",
      },
      {
        name: "حمار وحشي",
        enName: "Zebra",
        frName: "Zèbre",
        sound: "/sounds/learn-names/ar/wild-animals/zebra.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/zebra.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/zebra.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/zebra.png",
      },
      {
        name: "فرس النهر",
        enName: "Hippo",
        frName: "Hippopotame",
        sound: "/sounds/learn-names/ar/wild-animals/hippo.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/hippo.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/hippo.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/hippo.png",
      },
      {
        name: "كنغر",
        enName: "Kangaroo",
        frName: "Kangourou",
        sound: "/sounds/learn-names/ar/wild-animals/kangaroo.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/kangaroo.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/kangaroo.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/kangaroo.png",
      },
      {
        name: "ثعلب",
        enName: "Fox",
        frName: "Renard",
        sound: "/sounds/learn-names/ar/wild-animals/fox.mp3",
        enSound: "/sounds/learn-names/en/wild-animals/fox.mp3",
        frSound: "/sounds/learn-names/fr/wild-animals/fox.mp3",
        itemSound: null,
        image: "/images/learn-names/wild-animals/fox.png",
      },
    ],
  },
  {
    name: "في المطبخ",
    image: "/images/learn-names/kitchen/category.jpg",
    items: [
      {
        name: "ملعقة",
        enName: "Spoon",
        frName: "Cuillère",
        sound: "/sounds/learn-names/ar/kitchen/spoon.mp3",
        enSound: "/sounds/learn-names/en/kitchen/spoon.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/spoon.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/spoon.png",
      },
      {
        name: "شوكة",
        enName: "Fork",
        frName: "Fourchette",
        sound: "/sounds/learn-names/ar/kitchen/fork.mp3",
        enSound: "/sounds/learn-names/en/kitchen/fork.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/fork.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/fork.png",
      },
      {
        name: "سكين",
        enName: "Knife",
        frName: "Couteau",
        sound: "/sounds/learn-names/ar/kitchen/knife.mp3",
        enSound: "/sounds/learn-names/en/kitchen/knife.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/knife.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/knife.png",
      },
      {
        name: "طبق",
        enName: "Plate",
        frName: "Assiette",
        sound: "/sounds/learn-names/ar/kitchen/plate.mp3",
        enSound: "/sounds/learn-names/en/kitchen/plate.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/plate.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/plate.png",
      },
      {
        name: "كوب",
        enName: "Cup",
        frName: "Tasse",
        sound: "/sounds/learn-names/ar/kitchen/cup.mp3",
        enSound: "/sounds/learn-names/en/kitchen/cup.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/cup.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/cup.png",
      },
      {
        name: "طاولة",
        enName: "Table",
        frName: "Table",
        sound: "/sounds/learn-names/ar/kitchen/table.mp3",
        enSound: "/sounds/learn-names/en/kitchen/table.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/table.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/table.png",
      },
      {
        name: "كرسي",
        enName: "Chair",
        frName: "Chaise",
        sound: "/sounds/learn-names/ar/kitchen/chair.mp3",
        enSound: "/sounds/learn-names/en/kitchen/chair.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/chair.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/chair.png",
      },
      {
        name: "فرن",
        enName: "Oven",
        frName: "Four",
        sound: "/sounds/learn-names/ar/kitchen/oven.mp3",
        enSound: "/sounds/learn-names/en/kitchen/oven.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/oven.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/oven.png",
      },
      {
        name: "ثلاجة",
        enName: "Fridge",
        frName: "Réfrigérateur",
        sound: "/sounds/learn-names/ar/kitchen/fridge.mp3",
        enSound: "/sounds/learn-names/en/kitchen/fridge.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/fridge.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/fridge.png",
      },
      {
        name: "مغسلة",
        enName: "Sink",
        frName: "Évier",
        sound: "/sounds/learn-names/ar/kitchen/sink.mp3",
        enSound: "/sounds/learn-names/en/kitchen/sink.mp3",
        frSound: "/sounds/learn-names/fr/kitchen/sink.mp3",
        itemSound: null,
        image: "/images/learn-names/kitchen/sink.png",
      },
    ],
  },
  {
    name: "فواكه",
    image: "/images/learn-names/fruits/category.jpg",
    items: [
      {
        name: "تفاحة",
        enName: "Apple",
        frName: "Pomme",
        sound: "/sounds/learn-names/ar/fruits/apple.mp3",
        enSound: "/sounds/learn-names/en/fruits/apple.mp3",
        frSound: "/sounds/learn-names/fr/fruits/apple.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/apple.png",
      },
      {
        name: "موزة",
        enName: "Banana",
        frName: "Banane",
        sound: "/sounds/learn-names/ar/fruits/banana.mp3",
        enSound: "/sounds/learn-names/en/fruits/banana.mp3",
        frSound: "/sounds/learn-names/fr/fruits/banana.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/banana.png",
      },
      {
        name: "برتقالة",
        enName: "Orange",
        frName: "Orange",
        sound: "/sounds/learn-names/ar/fruits/orange.mp3",
        enSound: "/sounds/learn-names/en/fruits/orange.mp3",
        frSound: "/sounds/learn-names/fr/fruits/orange.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/orange.png",
      },
      {
        name: "فراولة",
        enName: "Strawberry",
        frName: "Fraise",
        sound: "/sounds/learn-names/ar/fruits/strawberry.mp3",
        enSound: "/sounds/learn-names/en/fruits/strawberry.mp3",
        frSound: "/sounds/learn-names/fr/fruits/strawberry.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/strawberry.png",
      },
      {
        name: "عنب",
        enName: "Grapes",
        frName: "Raisins",
        sound: "/sounds/learn-names/ar/fruits/grapes.mp3",
        enSound: "/sounds/learn-names/en/fruits/grapes.mp3",
        frSound: "/sounds/learn-names/fr/fruits/grapes.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/grapes.png",
      },
      {
        name: "بطيخ",
        enName: "Watermelon",
        frName: "Pastèque",
        sound: "/sounds/learn-names/ar/fruits/watermelon.mp3",
        enSound: "/sounds/learn-names/en/fruits/watermelon.mp3",
        frSound: "/sounds/learn-names/fr/fruits/watermelon.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/watermelon.png",
      },
      {
        name: "أناناس",
        enName: "Pineapple",
        frName: "Ananas",
        sound: "/sounds/learn-names/ar/fruits/pineapple.mp3",
        enSound: "/sounds/learn-names/en/fruits/pineapple.mp3",
        frSound: "/sounds/learn-names/fr/fruits/pineapple.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/pineapple.png",
      },
      {
        name: "إجاصة",
        enName: "Pear",
        frName: "Poire",
        sound: "/sounds/learn-names/ar/fruits/pear.mp3",
        enSound: "/sounds/learn-names/en/fruits/pear.mp3",
        frSound: "/sounds/learn-names/fr/fruits/pear.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/pear.png",
      },
      {
        name: "كرز",
        enName: "Cherry",
        frName: "Cerise",
        sound: "/sounds/learn-names/ar/fruits/cherry.mp3",
        enSound: "/sounds/learn-names/en/fruits/cherry.mp3",
        frSound: "/sounds/learn-names/fr/fruits/cherry.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/cherry.png",
      },
      {
        name: "خوخة",
        enName: "Peach",
        frName: "Pêche",
        sound: "/sounds/learn-names/ar/fruits/peach.mp3",
        enSound: "/sounds/learn-names/en/fruits/peach.mp3",
        frSound: "/sounds/learn-names/fr/fruits/peach.mp3",
        itemSound: null,
        image: "/images/learn-names/fruits/peach.png",
      },
    ],
  },
];

export const games = [
  {
    id: "sliding-puzzle",
    name: "لغز الانزلاق",
    image: "/images/games/sliding.png",
    description: "رتب القطع لتكوين الترتيب أو الصورة الصحيحة.",
  },
  {
    id: "matching-cards",
    name: "بطاقات المطابقة",
    image: "/images/games/matching.png",
    description: "ابحث عن أزواج البطاقات المتطابقة — أرقام، حروف أو صور.",
  },
  {
    id: "sound-matching",
    name: "التعرف على الأصوات",
    image: "/images/games/sound.png",
    description: "استمع لصوت واختر الصورة المطابقة.",
  },
  {
    id: "drag-labeling",
    name: "سحب التسميات",
    image: "/images/games/drag.png",
    description: "اسحب التسميات إلى الصور لتطابق الكلمات مع الصور.",
  },
  {
    id: "sequence-builder",
    name: "بناء التسلسل",
    image: "/images/games/sequence.png",
    description: "شاهد نمطًا قصيرًا ثم أعده — يزيد الطول تدريجيًا.",
  },
  {
    id: "puzzle-assembly",
    name: "تركيب الأشكال",
    image: "/images/games/puzzle.png",
    description: "اسحب قطعًا لتجميع الشكل: تلتصق القطع عندما تكون قريبة.",
  },
  {
    id: "addition-game",
    name: "تحدي الرياضيات : الجمع",
    image: "/images/games/addition.png",
    description: "اختر الناتج الصحيح لمعادلة جمع بسيطة.",
  },
  {
    id: "multiplication-game",
    name: "تحدي الرياضيات : الضرب",
    image: "/images/games/multiplication.png",
    description: "اختر الناتج الصحيح لمعادلة ضرب بسيطة.",
  },
  {
    id: "number-line-jump",
    name: "القفز على خط الأرقام",
    image: "/images/games/number-line-jump.png",
    description: "اقفز إلى الرقم الصحيح لحل مسائل الجمع والطرح.",
  },
  {
    id: "math-bingo",
    name: "البينغو الرياضي",
    image: "/images/games/math-bingo.png",
    description: "احسب المسائل الرياضية واختر الإجابات الصحيحة من كارت البينغو.",
  },
  {
    id: "equation-balance",
    name: "ميزان المعادلات",
    image: "/images/games/equation-balance.png",
    description: "أوجد القيمة المفقودة لتوازن الميزان وحل المعادلات.",
  },
  {
    id: "missing-number-game",
    name: "الأرقام المفقودة",
    image: "/images/games/missing-number-game.png",
    description: "املأ الرقم المفقود في التسلسل العددي.",
  },
  {
    id: "shape-builder",
    name: "بناء الأشكال",
    image: "/images/games/shape-builder.png",
    description: "اربط النقاط لتكوين أشكال هندسية مختلفة.",
  },
  {
    id: "shape-classifier",
    name: "تصنيف الأشكال",
    image: "/images/games/shape-classifier.png",
    description: "صنف الأشكال الهندسية حسب خصائصها مثل عدد الأضلاع والزوايا.",
  },
  {
    id: "area-calculator",
    name: "حاسبة المساحة والمحيط",
    image: "/images/games/area-calculator.png",
    description: "تعلم حساب المساحة والمحيط باستخدام الشبكة المربعة.",
  },
  {
    id: "angle-hunter",
    name: "صياد الزوايا",
    image: "/images/games/angle-hunter.png",
    description: "تعرف على أنواع الزوايا المختلفة وتعلم قياسها.",
  },
  {
    id: "pizza-fractions",
    name: "كسور البيتزا",
    image: "/images/games/pizza-fractions.png",
    description: "تعلم الكسور من خلال تقطيع البيتزا ومطابقة المسائل.",
  },
  {
    id: "fraction-comparison",
    name: "مقارنة الكسور",
    image: "/images/games/fraction-comparison.png",
    description: "قارن الكسور باستخدام الرسوم البيانية الدائرية البصرية.",
  },
    
];

export const otherGames = [
  {
    id: "fruits-collect",
    name: "جمع الفواكه",
    image:
      "https://img.itch.zone/aW1nLzE3MjAzMTM3LnBuZw==/315x250%23c/NsiAZN.png",
    itchGameId: "fruits-collector",
    itchEmbedId: "11319496",
  },
  {
    id: "flyin-ship",
    name: "السفينة الطائرة",
    image:
      "https://img.itch.zone/aW1nLzE3MjgxOTgyLnBuZw==/315x250%23c/0l0mGg.png",
    itchGameId: "2889611",
    itchEmbedId: "11317620",
  },
  {
    id: "Tetris",
    name: "تتريس",
    image: "https://img.itch.zone/aW1nLzY2MDU3NzEucG5n/315x250%23c/Zgjb1x.png",
    itchGameId: "tetris3d",
    itchEmbedId: "4221680",
  },
  {
    id: "maze-learn",
    name: "متاهة التعلم",
    image: "https://img.itch.zone/aW1nLzYyNjgyNTEucG5n/315x250%23c/8r5lig.png",
    itchGameId: "maze-learn",
    itchEmbedId: "11191210",
  },
  ,
  {
    id: "taallam-platformer",
    name: "مغامرة التعلم",
    image: "https://img.itch.zone/aW1nLzIyOTI1NjUxLnBuZw==/315x250%23c/9sMq%2FH.png",
    itchGameId: "taallam-platformer",
    itchEmbedId: "14810943",
  }
];
